[project]
name = "mt-rag-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.4.0",
    "beautifulsoup4>=4.14.2",
    "bert-score>=0.3.13",
    "evaluate==0.4.3",
    "langchain-community==0.2.19",
    "langchain==0.2.17",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "protobuf==5.29.3",
    "pytrec-eval==0.5",
    "ragas==0.3.3",
    "rouge-score>=0.1.2",
    "sentencepiece==0.2.0",
    #    "torch==2.8.0",
    "tqdm>=4.67.1",
    #    "bitsandbytes==0.47.0",
    "pydantic==2.11.7",
    #    "flash-attn==2.8.3",
    "python-dotenv>=1.2.1",
    "google-genai>=1.50.1",
    "qdrant-client>=1.12.1",
    "sentence-transformers>=5.1.2",
    "rank-bm25>=0.2.2",
    "tenacity>=8.5.0",
    "dspy==3.1.2",
    "mlflow>=3.8.1",
]
